version: 0.2

phases:
  install:
    commands:
      - if [ -e /tmp/node_modules.tar ]; then tar xf /tmp/node_modules.tar; fi
      - npm install

  pre_build:
    commands:
      - true

  build:
    commands:
      - true

  post_build:
    commands:
      - tar cf /tmp/node_modules.tar node_modules

artifacts:
  files: ['**/*']

cache:
  paths:
    - /tmp/node_modules.tar
